### PR TITLE
Add ARCore demo project

### PR DESCRIPTION
**Pull request by BastiaanOlij**
Adding a demo project into this. For now this is a direct copy of the original ARCore demo used to test the ARCore module with the addons folder added. It needs to be tweaked further to make it work and then turned into a nicer demo.

### CODE REVIEW

**Comment by BastiaanOlij** [comment]
Rebased this and running through @m4gr3d  latest instructions, nearly got it to work.  
Had to go to the latest godot-cpp master or it wouldn't compile, now getting stuck running gradlew becomes I don't think it's adding godot-headers to the include path.

**Comment by BastiaanOlij** [comment]
Haven't finished the work yet but converting from an ARVRInterface subclass to an ARVRInterface GDNative structure, Godot can't actually call our methods because GDNative isn't true subclassing but a bridge to methods for Godots interpreter which isn't used by the rendering engine. 

Did the first pass, still dealing with all the compiler errors for things I've missed.

**Review by m4gr3d — CHANGES_REQUESTED** [review]
@BastiaanOlij You can leave the `arcore_interface` class as is and instead add a class that'll proxy for the C bindings.
It'll be similar to what we do for the Quest plugin with the `arcore_interface` class taking the role of `ovr_mobile_session` here.

**Comment by m4gr3d** [comment]
@BastiaanOlij Can you split the update to `arcore_interface` to another PR and have this one just focused on adding the demo. 
The changes I suggested should be small so that would bring better clarity to each PR.

**Comment by BastiaanOlij** [comment]
I'll have to figure out if I can pull the changes apart, the problem is that I need the demo to test the changes and I need the changes to test the demo :)

**Comment by BastiaanOlij** [comment]
Ok, removed the code for changing the interface out of this PR, will be taking a different approach. Also merged the two commits

**Comment by BastiaanOlij** [comment]
Ok, moved all the other changes that are unrelated to the demo too. Still more work to do on the demo itself, but first going to work on making it run.

**Comment by BastiaanOlij** [comment]
I'm merging this in so we have a demo to test against.

**Pull request merged**
